### ISSUE TITLE
When printing Income Statement 12 Columns Report Following Trace-back is presented

### ISSUE THREAD

**Issue by hbto** [Vauxoo/odoo-ifrs#5]
2014-11-02 06:20:29,338 10031 ERROR v8_ifrs werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/hbto/_git_projects/odoo/openerp/service/server.py", line 280, in app
    return self.app(e, s)
  File "/home/hbto/_git_projects/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/home/hbto/_git_projects/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/home/hbto/_git_projects/odoo/openerp/http.py", line 1215, in __call__
    return self.dispatch(environ, start_response)
  File "/home/hbto/_git_projects/odoo/openerp/http.py", line 1189, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in **call**
    return self.app(environ, start_response)
  File "/home/hbto/_git_projects/odoo/openerp/http.py", line 1189, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in **call**
    return self.app(environ, start_response)
  File "/home/hbto/_git_projects/odoo/openerp/http.py", line 1356, in dispatch
    result = ir_http._dispatch()
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_http.py", line 130, in _dispatch
    return self._handle_exception(e)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_http.py", line 100, in _handle_exception
    return request._handle_exception(exception)
  File "/home/hbto/_git_projects/odoo/openerp/http.py", line 596, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_http.py", line 126, in _dispatch
    result = request.dispatch()
  File "/home/hbto/_git_projects/odoo/openerp/http.py", line 614, in dispatch
    r = self._call_function(*_self.params)
  File "/home/hbto/_git_projects/odoo/openerp/http.py", line 283, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/hbto/_git_projects/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/hbto/_git_projects/odoo/openerp/http.py", line 280, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/hbto/_git_projects/odoo/openerp/http.py", line 733, in __call__
    return self.method(_args, *_kw)
  File "/home/hbto/_git_projects/odoo/openerp/http.py", line 376, in response_wrap
    response = f(_args, *_kw)
  File "/home/hbto/_git_projects/odoo/addons/report/controllers/main.py", line 121, in report_download
    response = self.report_routes(reportname, converter='pdf', *_dict(data))
  File "/home/hbto/_git_projects/odoo/openerp/http.py", line 376, in response_wrap
    response = f(_args, *_kw)
  File "/home/hbto/_git_projects/odoo/addons/report/controllers/main.py", line 64, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
  File "/home/hbto/_git_projects/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, *_kwargs)
  File "/home/hbto/_git_projects/odoo/addons/report/models/report.py", line 183, in get_pdf
    html = self.get_html(cr, uid, ids, report_name, data=data, context=context)
  File "/home/hbto/_git_projects/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/hbto/_git_projects/odoo/addons/report/models/report.py", line 158, in get_html
    return particularreport_obj.render_html(cr, uid, ids, data=data, context=context)
  File "/home/hbto/_git_projects/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/hbto/_git_projects/odoo/addons/report/models/abstract_report.py", line 64, in render_html
    return self.pool['report'].render(cr, uid, [], self._template, docargs, context=context)
  File "/home/hbto/_git_projects/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/hbto/_git_projects/odoo/addons/report/models/report.py", line 144, in render
    return view_obj.render(cr, uid, template, values, context=context)
  File "/home/hbto/_git_projects/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1007, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/home/hbto/_git_projects/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 426, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 416, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 361, in render_tag_raw
    inner = self.eval_str(template_attributes["raw"], qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 205, in eval_str
    val = self.eval(expr, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 197, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 194, in eval
    return qwebcontext.safe_eval(expr)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 80, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/home/hbto/_git_projects/odoo/openerp/tools/safe_eval.py", line 313, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>

  File "/home/hbto/_git_projects/odoo/addons/report/models/report.py", line 128, in translate_doc
    return view_obj.render(cr, uid, template, qcontext, context=ctx)
  File "/home/hbto/_git_projects/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_ui_view.py", line 1007, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/home/hbto/_git_projects/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 253, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 426, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 416, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 421, in render_tag_if
    return self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 416, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 421, in render_tag_if
    return self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 421, in render_tag_if
    return self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 416, in render_tag_foreach
    ru.append(self.render_element(element, template_attributes, generated_attributes, copy_qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 294, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 421, in render_tag_if
    return self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 421, in render_tag_if
    return self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 315, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 292, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 367, in render_tag_esc
    inner = widget.format(template_attributes['esc'], options, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 985, in format
    return escape(self._format(inner, options, qwebcontext))
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 982, in _format
    return self.pool['ir.qweb'].eval_str(inner, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 205, in eval_str
    val = self.eval(expr, qwebcontext)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 197, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 194, in eval
    return qwebcontext.safe_eval(expr)
  File "/home/hbto/_git_projects/odoo/openerp/addons/base/ir/ir_qweb.py", line 80, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/home/hbto/_git_projects/odoo/openerp/tools/safe_eval.py", line 311, in safe_eval
    c = test_expr(expr, _SAFE_OPCODES, mode=mode)
  File "/home/hbto/_git_projects/odoo/openerp/tools/safe_eval.py", line 166, in test_expr
    code_obj = compile(expr, "", mode)
QWebException: "invalid syntax
('', 1, 39, "ifrs_l['period'][month] or 0.0, digits=2, grouping=3, monetary=True)")" while evaluating
"translate_doc(doc_id, doc_model, 'company_id.partner_id.lang', 'ifrs_report.ifrs_document')"

**Comment by hbto** [comment]
Fixed with PR https://github.com/Vauxoo/odoo-ifrs/pull/12
